// OCR识别图片
async function ocrImage(file) {
    return new Promise((resolve) => {
        Tesseract.recognize(
            file,
            'eng+chi_sim',
            {
                logger: m => console.log(m)
            }
        ).then(({ data: { text } }) => {
            resolve(text);
        });
    });
}

// 主函数（先做“模拟解析”）
document.getElementById("analyzeBtn").addEventListener("click", async () => {

    let text = document.getElementById("questionInput").value;
    const file = document.getElementById("imageInput").files[0];

    // 如果有图片就OCR
    if (file) {
        text = await ocrImage(file);
    }

    // ===== 这里先做“假数据”，后面接AI =====
    document.getElementById("type").innerText = "力学 / Mechanics";
    document.getElementById("knowledge").innerText = "牛顿第二定律 F=ma";
    document.getElementById("cn").innerText = "这里是中文解析（等待接入AI）";
    document.getElementById("en").innerText = "English explanation will be generated by AI later.";
    document.getElementById("history").innerText = "牛顿在1687年提出经典力学体系。";

});